# Generated by Django 5.2 on 2025-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicalwork',
            name='sequence_number',
            field=models.IntegerField(unique=True),
        ),
    ]
