# Generated by Django 5.2 on 2025-05-16 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue_app', '0004_alter_practicalwork_sequence_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailchangeattempt',
            old_name='attempts',
            new_name='resend_count',
        ),
        migrations.RemoveField(
            model_name='emailchangeattempt',
            name='last_attempt',
        ),
        migrations.AddField(
            model_name='emailchangeattempt',
            name='last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailchangeattempt',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_attempt', to=settings.AUTH_USER_MODEL),
        ),
    ]
