# Generated by Django 5.2 on 2025-05-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue_app', '0007_telegramchangeattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email_notifications',
            new_name='browser_notifications',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_position_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_position_3_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_position_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='browser_queue_join_leave',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_position_1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_position_3_2',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_position_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram_queue_join_leave',
            field=models.BooleanField(default=True),
        ),
    ]
