# Generated by Django 5.2.1 on 2025-05-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue_app', '0010_telegramverificationattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistparticipant',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
