# Generated by Django 5.2.1 on 2025-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_queue_app', '0011_waitinglistparticipant_modified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicalwork',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
